server:
  port: 8081
    
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: Achan$098
    
  
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      
transaction-service:
 ribbon:
    listOfServers: http://localhost:8082